name:                lysse
version:             0.1.0.0
github:              "sahithyen/lysse"
license:             BSD3
author:              "Sahithyen Kanaganayagam"
maintainer:          "mail@sahithyen.com"
copyright:           "2023 Sahithyen Kanaganayagam"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/lysse#readme>

dependencies:
- base >= 4.7 && < 5
- binary
- bytestring
- containers
- mtl
- text
- argparser

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: [src, src/generation, src/parser]

executables:
  lyc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lysse

tests:
  lysse-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lysse
